# Generated by Django 3.1.7 on 2021-04-27 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('recipe', models.URLField()),
                ('image', models.URLField(blank=True, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('weather', models.CharField(choices=[('rainy', 'Wet and rainy'), ('cloudy', 'Cloudy and overcast'), ('grey', 'Grey and gloomy'), ('snow', 'Snowing'), ('sunny', 'Sunny'), ('windy', 'Windy'), ('warm', 'Warm'), ('cold', 'Cold'), ('humid', 'Humid'), ('dry', 'Dry'), ('fog', 'Fog')], max_length=64)),
                ('diets', models.CharField(choices=[('none', 'N/A'), ('carnivore', 'Carnivore'), ('diabetic', 'Diabetic'), ('gluten_free', 'Gluten-Free'), ('keto', 'Keto'), ('light', 'Light'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian')], max_length=64)),
                ('meals', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('desserts', 'Desserts'), ('brunch', 'Brunch'), ('drinks', 'Drinks'), ('snacks', 'Snacks')], max_length=64)),
                ('food_type', models.ManyToManyField(to='core.Food_Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
