# Generated by Django 3.1.7 on 2021-04-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210427_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='weather',
        ),
        migrations.AddField(
            model_name='recipe',
            name='weather',
            field=models.ManyToManyField(related_name='recipes', to='core.Weather'),
        ),
    ]
