# Generated by Django 3.1.7 on 2021-04-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210427_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='food_type',
            field=models.CharField(choices=[('african', 'African'), ('american', 'American'), ('british', 'British'), ('chinese', 'Chinese'), ('eastern_european', 'Eastern European'), ('french', 'French'), ('greek', 'Greek'), ('italian', 'Italian'), ('indian', 'Indian'), ('japanese', 'Japanese'), ('mexican', 'Mexican'), ('middle_eastern', 'Middle Eastern'), ('nordic', 'Nordic'), ('persian', 'Persian'), ('south_american', 'South American'), ('thai', 'Thai'), ('vietnamese', 'Vietnamese')], max_length=64),
        ),
    ]
