# Generated by Django 3.1.7 on 2021-04-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210429_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='food_type',
            field=models.CharField(choices=[('African', 'African'), ('American', 'American'), ('British', 'British'), ('Chinese', 'Chinese'), ('Eastern European', 'Eastern European'), ('French', 'French'), ('Greek', 'Greek'), ('Italian', 'Italian'), ('Indian', 'Indian'), ('Japanese', 'Japanese'), ('Mexican', 'Mexican'), ('Middle Eastern', 'Middle Eastern'), ('Nordic', 'Nordic'), ('Persian', 'Persian'), ('South American', 'South American'), ('Thai', 'Thai'), ('Vietnamese', 'Vietnamese')], max_length=64),
        ),
    ]
