# Generated by Django 3.1.7 on 2021-05-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210430_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='diets',
            field=models.CharField(choices=[('None', 'None'), ('Carnivore', 'Carnivore'), ('Diabetic', 'Diabetic'), ('Gluten Free', 'Gluten Free'), ('Keto', 'Keto'), ('Light', 'Light'), ('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian')], max_length=64),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meals',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Desserts', 'Desserts'), ('Brunch', 'Brunch'), ('Drinks', 'Drinks'), ('Snacks', 'Snacks')], max_length=64),
        ),
    ]
